# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batting',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, primary_key=True, verbose_name='ID')),
                ('season', models.IntegerField(db_column='Season')),
                ('team', models.CharField(max_length=12, db_column='Team')),
                ('g', models.IntegerField(db_column='G')),
                ('ab', models.IntegerField(db_column='AB')),
                ('pa', models.IntegerField(db_column='PA')),
                ('h', models.IntegerField(db_column='H')),
                ('singles', models.IntegerField(db_column='1B')),
                ('doubles', models.IntegerField(db_column='2B')),
                ('triples', models.IntegerField(db_column='3B')),
                ('hr', models.IntegerField(db_column='HR')),
                ('r', models.IntegerField(db_column='R')),
                ('rbi', models.IntegerField(db_column='RBI')),
                ('bb', models.IntegerField(db_column='BB')),
                ('ibb', models.IntegerField(db_column='IBB')),
                ('so', models.IntegerField(db_column='SO')),
                ('hbp', models.IntegerField(db_column='HBP')),
                ('sf', models.IntegerField(db_column='SF')),
                ('sh', models.IntegerField(db_column='SH')),
                ('gdp', models.IntegerField(db_column='GDP')),
                ('sb', models.IntegerField(db_column='SB')),
                ('cs', models.IntegerField(db_column='CS')),
                ('avg', models.DecimalField(max_digits=65, decimal_places=30, db_column='AVG')),
                ('obp', models.DecimalField(max_digits=65, decimal_places=30, db_column='OBP')),
                ('slg', models.DecimalField(max_digits=65, decimal_places=30, db_column='SLG')),
                ('ops', models.DecimalField(max_digits=65, decimal_places=30, db_column='OPS')),
                ('iso', models.DecimalField(max_digits=65, decimal_places=30, db_column='ISO')),
                ('babip', models.DecimalField(max_digits=65, decimal_places=30, db_column='BABIP')),
                ('woba', models.DecimalField(max_digits=65, decimal_places=30, db_column='wOBA')),
                ('wraa', models.DecimalField(max_digits=12, decimal_places=2, db_column='wRAA')),
                ('wrc', models.IntegerField(db_column='wRC')),
                ('rar', models.DecimalField(max_digits=12, decimal_places=2, db_column='RAR')),
                ('waroff', models.DecimalField(max_digits=12, decimal_places=2, db_column='WARoff')),
                ('wrc_field', models.IntegerField(db_column='wRC+')),
                ('wsb', models.DecimalField(max_digits=12, decimal_places=2, db_column='wSB')),
            ],
        ),
        migrations.CreateModel(
            name='Fielding',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, primary_key=True, verbose_name='ID')),
                ('season', models.IntegerField(db_column='Season')),
                ('team', models.CharField(max_length=12, db_column='Team')),
                ('inn', models.IntegerField(db_column='Inn')),
                ('po', models.IntegerField(db_column='PO')),
                ('a', models.IntegerField(db_column='A')),
                ('e', models.IntegerField(db_column='E')),
                ('dp', models.IntegerField(db_column='DP')),
                ('sb', models.IntegerField(db_column='SB')),
                ('cs', models.IntegerField(db_column='CS')),
                ('pb', models.IntegerField(db_column='PB')),
                ('wp', models.IntegerField(db_column='WP')),
                ('fp', models.DecimalField(max_digits=65, decimal_places=30, db_column='FP')),
            ],
        ),
        migrations.CreateModel(
            name='Pitching',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, primary_key=True, verbose_name='ID')),
                ('season', models.IntegerField(db_column='Season')),
                ('team', models.CharField(max_length=12, db_column='Team')),
                ('w', models.IntegerField(db_column='W')),
                ('l', models.IntegerField(db_column='L')),
                ('era', models.DecimalField(max_digits=12, decimal_places=2, db_column='ERA')),
                ('g', models.IntegerField(db_column='G')),
                ('gs', models.IntegerField(db_column='GS')),
                ('cg', models.IntegerField(db_column='CG')),
                ('sho', models.IntegerField(db_column='ShO')),
                ('sv', models.IntegerField(db_column='SV')),
                ('ip', models.DecimalField(max_digits=12, decimal_places=2, db_column='IP')),
                ('tbf', models.IntegerField(db_column='TBF')),
                ('h', models.IntegerField(db_column='H')),
                ('r', models.IntegerField(db_column='R')),
                ('er', models.IntegerField(db_column='ER')),
                ('hr', models.IntegerField(db_column='HR')),
                ('bb', models.IntegerField(db_column='BB')),
                ('ibb', models.IntegerField(db_column='IBB')),
                ('hbp', models.IntegerField(db_column='HBP')),
                ('wp', models.IntegerField(db_column='WP')),
                ('so', models.IntegerField(db_column='SO')),
                ('avg', models.DecimalField(max_digits=65, decimal_places=30, db_column='AVG')),
                ('whip', models.DecimalField(max_digits=12, decimal_places=2, db_column='WHIP')),
                ('babip', models.DecimalField(max_digits=65, decimal_places=30, db_column='BABIP')),
                ('lob', models.DecimalField(max_digits=65, decimal_places=30, db_column='LOB%')),
                ('fip', models.DecimalField(max_digits=12, decimal_places=2, db_column='FIP')),
                ('rar', models.DecimalField(max_digits=12, decimal_places=2, db_column='RAR')),
                ('war', models.DecimalField(max_digits=12, decimal_places=2, db_column='WAR')),
            ],
        ),
    ]
